In [1]:
import pandas as pd
import numpy as np

In [2]:
fake=pd.read_csv('DATASET/fake.csv')

In [3]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [4]:
fake['label']=0

In [5]:
true=pd.read_csv('DATASET/true.csv')

In [6]:
true['text']

0        WASHINGTON (Reuters) - The head of a conservat...
1        WASHINGTON (Reuters) - Transgender people will...
2        WASHINGTON (Reuters) - The special counsel inv...
3        WASHINGTON (Reuters) - Trump campaign adviser ...
4        SEATTLE/WASHINGTON (Reuters) - President Donal...
                               ...
21412    BRUSSELS (Reuters) - NATO allies on Tuesday we...
21413    LONDON (Reuters) - LexisNexis, a provider of l...
21414    MINSK (Reuters) - In the shadow of disused Sov...
21415    MOSCOW (Reuters) - Vatican Secretary of State ...
21416    JAKARTA (Reuters) - Indonesia will buy 11 Sukh...
Name: text, Length: 21417, dtype: object

In [7]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [8]:
true['label']=1

In [9]:
#concat true and fake news row wise
news=pd.concat([true,fake], axis=0)

In [2]:
news=pd.read_csv('news.csv')

In [3]:
news.head()

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [4]:
news.tail()

,Unnamed: 0,title,text,label
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [5]:
news.isnull().sum()

Unnamed: 0    0
title         0
text          0
label         0
dtype: int64

In [6]:
#do feature selection
news=news.drop(['title'],axis=1)

In [7]:
news=news.sample(frac=1)                    #reshuffle 
news.reset_index(inplace=True)
news=news.drop(['index'],axis=1)

In [8]:
news

      Unnamed: 0                                               text label
0           4109  Republicans have never passed an Obamacare rep...  REAL
1           3265  Eight years after he was the Republican presid...  REAL
2           6322  Region: Eastern Asia While observing the react...  FAKE
3            299  The fledgling rebellion against electing John ...  REAL
4           7620  Ever since Wikileaks and hacking groups began ...  FAKE
...          ...                                                ...   ...
6330        9702  A collection of thoughts about American foreig...  FAKE
6331        1326  4 Things The New Hampshire Primary Will Tell U...  REAL
6332       10425  Common painkillers linked to increased heart f...  FAKE
6333        3824  2015 has been an eventful year for Barack Obam...  REAL
6334        3960  France's bid to unite the world against the Is...  REAL

[6335 rows x 3 columns]

In [9]:
#import regular expression module 
import re

In [10]:
def wordopt(text):
    #convert into lowercase 
    text=text.lower()

    #remove URLs
    text=re.sub(r'https?://S+|www\.\S+','',text)

    #remove HTML tags
    text=re.sub(r'<.*?>','',text)

    #remove punctuation
    text=re.sub(r'[^\w\s]','',text)

    #remove digits
    text=re.sub(r'\d','',text)

    #remove newline charcters
    text=re.sub(r'\n',' ',text)

    return text

In [11]:
news['text']=news['text'].apply(wordopt)

In [12]:
news['text']

0       republicans have never passed an obamacare rep...
1       eight years after he was the republican presid...
2       region eastern asia while observing the reacti...
3       the fledgling rebellion against electing john ...
4       ever since wikileaks and hacking groups began ...
                              ...
6330    a collection of thoughts about american foreig...
6331     things the new hampshire primary will tell us...
6332    common painkillers linked to increased heart f...
6333     has been an eventful year for barack obama he...
6334    frances bid to unite the world against the isl...
Name: text, Length: 6335, dtype: object

In [13]:
x=news['text']
y=news['label']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [16]:
x_train.shape

(4434,)

In [17]:
x_test.shape

(1901,)

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [19]:
vectorization=TfidfVectorizer()

In [20]:
xv_train=vectorization.fit_transform(x_train)

In [21]:
xv_test=vectorization.transform(x_test)

In [22]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1482882 stored elements and shape (4434, 69970)>

In [23]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 637241 stored elements and shape (1901, 69970)>

In [24]:
#build logistic regression model
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [25]:
lr.fit(xv_train,y_train)

LogisticRegression()

In [26]:
pred_lr=lr.predict(xv_test)

In [27]:
from sklearn.metrics import accuracy_score,classification_report
print(classification_report(y_test, pred_lr))
print('Accuracy:',100*accuracy_score(y_test,pred_lr))

              precision    recall  f1-score   support

        FAKE       0.89      0.93      0.91       907
        REAL       0.94      0.89      0.91       994

    accuracy                           0.91      1901
   macro avg       0.91      0.91      0.91      1901
weighted avg       0.91      0.91      0.91      1901

Accuracy: 91.21514992109417

In [28]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

In [29]:
dt.fit(xv_train,y_train)

DecisionTreeClassifier()

In [30]:
pred_dt=dt.predict(xv_test)

In [31]:
print(classification_report(y_test, pred_dt))
print('Accuracy:',100*accuracy_score(y_test,pred_dt))

              precision    recall  f1-score   support

        FAKE       0.77      0.79      0.78       907
        REAL       0.81      0.78      0.79       994

    accuracy                           0.79      1901
   macro avg       0.79      0.79      0.79      1901
weighted avg       0.79      0.79      0.79      1901

Accuracy: 78.59021567596002

In [32]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()

In [33]:
rf.fit(xv_train,y_train)

RandomForestClassifier()

In [34]:
pred_rf=rf.predict(xv_test)

In [35]:
print(classification_report(y_test, pred_rf))
print('Accuracy:',100*accuracy_score(y_test,pred_rf))

              precision    recall  f1-score   support

        FAKE       0.86      0.91      0.88       907
        REAL       0.91      0.86      0.88       994

    accuracy                           0.88      1901
   macro avg       0.88      0.88      0.88      1901
weighted avg       0.88      0.88      0.88      1901

Accuracy: 88.26933193056287

In [36]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier()

In [37]:
gb.fit(xv_train,y_train)

GradientBoostingClassifier()

In [38]:
pred_gb=gb.predict(xv_test)

In [39]:
print(classification_report(y_test, pred_gb))
print('Accuracy:',100*accuracy_score(y_test,pred_gb))

              precision    recall  f1-score   support

        FAKE       0.86      0.92      0.89       907
        REAL       0.92      0.86      0.89       994

    accuracy                           0.89      1901
   macro avg       0.89      0.89      0.89      1901
weighted avg       0.89      0.89      0.89      1901

Accuracy: 88.79537085744344

In [40]:
def output_label(n):
    if n=='FAKE':
        return "It is a fake news"
    elif n=='REAL':
        return "It is a genuine news"

In [41]:
def manual_testing(news):
    testing_news = {"text": [news]}

    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(wordopt)

    new_x_test = new_def_test["text"]

    # Assuming vectorization is your trained vectorizer
    new_xv_test = vectorization.transform(new_x_test)

    pred_lr = lr.predict(new_xv_test)
    pred_dt = dt.predict(new_xv_test)
    pred_gb = gb.predict(new_xv_test)
    pred_rf = rf.predict(new_xv_test)

    return (
        "\nLR Prediction: {}"
        "\nDT Prediction: {}"
        "\nGB Prediction: {}"
        "\nRF Prediction: {}"
    ).format(
        output_label(pred_lr),
        output_label(pred_dt),
        output_label(pred_gb),
        output_label(pred_rf)
    )

In [46]:
news = input("Enter news: ")
print(manual_testing(news))

Enter news:  Police say Siya Goyal used a sit-down signal to boyfriend Chetan Chaudhary before Ketan Agarwal was pushed off Lohagad Fort. Investigators claim the pair planned the killing carefully, practised beforehand and tried to avoid detection.

LR Prediction: It is a fake news
DT Prediction: It is a fake news
GB Prediction: It is a fake news
RF Prediction: It is a fake news

In [53]:
sample = vectorization.transform([news])

print("Non-zero features:", sample.nnz)
print("Total features:", sample.shape[1])

Non-zero features: 11
Total features: 176573